# 2. Numpy 배열

* NumPY에는 ndarray라는 데이터 타입의 배열이 생성된다.
* ndarray는 같은 타입의 데이터만 저장할 수 있다.

In [1]:
# import하기
import numpy as np

## 2-1. np.array() 함수로 생성하기
### 1차원 배열 생성하기

In [2]:
# 1차원 배열
arr = np.array([1, 2, 3, 4])
arr

array([1, 2, 3, 4])

In [3]:
# data type
arr.dtype

dtype('int32')

In [4]:
# overflow 테스트
arr = np.array([2147483648, 2, 3, 4])
arr

array([2147483648,          2,          3,          4], dtype=int64)

In [5]:
arr = np.array([1, 2, 3, 4], dtype=float)
arr

array([1., 2., 3., 4.])

In [6]:
arr.dtype

dtype('float64')

In [7]:
# shape : 각 차원의 배열의 size (모양)
arr.shape

(4,)

In [8]:
# size : 배열의 전체 element 수
arr.size

4

In [9]:
# ndim : 차원의 수
arr.ndim

1

In [10]:
arr = np.array([1, 2, 3, 3.14])
arr

array([1.  , 2.  , 3.  , 3.14])

In [11]:
arr = np.array([1, 2, 3, 3.14], dtype=int)
arr

array([1, 2, 3, 3])

In [12]:
# > : big-endian, < : little-endian
arr = np.array([1, 3.14, '1234'])
arr

array(['1', '3.14', '1234'], dtype='<U32')

In [13]:
arr = np.array([1, 3.14, '123456789012345678901234576890123'])
arr

array(['1', '3.14', '123456789012345678901234576890123'], dtype='<U33')

In [14]:
# 이미 있는 배열을 타입이 다른 배열로 생성하기
new_arr = arr.astype(float)
new_arr

array([1.00000000e+00, 3.14000000e+00, 1.23456789e+32])

In [15]:
arr.dtype, new_arr.dtype

(dtype('<U33'), dtype('float64'))

In [16]:
arr = np.array([1, 2, 3, 4])
arr2 = np.array([1, 2, 3, 4])
new_arr = np.array([arr, arr2])
new_arr

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

## 2차원 배열 생성하기

In [17]:
arr2 = np.array([[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12]], dtype=float)
arr2

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

In [18]:
arr2.dtype, arr2.shape, arr2.size, arr2.ndim

(dtype('float64'), (3, 4), 12, 2)

In [19]:
new_arr = arr2.astype(int)
new_arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

## 2-2. np.arange() 함수로 생성하기

In [20]:
# 파이썬의 range
for i in range(0, 10, 2):
    print(i)

0
2
4
6
8


### 1차원 배열 생성하기

In [21]:
arr = np.arange(1, 11, 2)
arr

array([1, 3, 5, 7, 9])

### 2차원 배열 생성하기

In [22]:
arr = np.arange(0, 12)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [23]:
arr2 = arr.reshape((3, 4))
arr2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [24]:
# arr2 = arr.reshape((3, 5))
# arr2

In [25]:
# 원본 배열의 shape를 변경하고자 할 경우
arr.shape = (3, 4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

## 2-3. np.zeros() 함수

In [26]:
# 1차원 배열
arr = np.zeros(4)
arr

array([0., 0., 0., 0.])

In [27]:
# 2차원 배열
arr2 = np.zeros((3, 4))
arr2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

## 2-4. np.ones() 함수

In [28]:
# 1차원 배열
arr = np.ones(4)
arr

array([1., 1., 1., 1.])

In [29]:
# 2차원 배열
arr2 = np.ones((3, 4))
arr2

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

## 2-5. np.linspace() 함수

In [30]:
arr = np.linspace(0, 10, 5)
arr

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [31]:
arr = np.linspace(0, 10)
arr

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [32]:
arr.shape

(50,)

In [33]:
arr2 = arr.reshape((10, 5))
arr2

array([[ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653],
       [ 1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469],
       [ 2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286],
       [ 3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102],
       [ 4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918],
       [ 5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735],
       [ 6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551],
       [ 7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367],
       [ 8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184],
       [ 9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ]])

### 2-6. np.full() 함수

In [34]:
# 특정 값으로 배열을 생성할 경우
arr = np.full(4, 10)
arr

array([10, 10, 10, 10])

In [35]:
arr2 = np.full((3, 4), 10)
arr2

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

## 2-7. np.eye() 함수

In [36]:
# 단위행렬 (항등행렬)
arr = np.eye(5)
arr

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## 2-8. np.random()을 이용

In [37]:
arr = np.random.rand(4)
arr

array([0.22825125, 0.50133737, 0.85527341, 0.57883208])

In [38]:
arr2 = np.random.rand(3, 4)
arr2

array([[0.1976314 , 0.29253451, 0.57526947, 0.77694804],
       [0.66386495, 0.79416747, 0.39833978, 0.42845769],
       [0.06238206, 0.22152929, 0.95750097, 0.30949646]])

In [39]:
arr = np.random.randint(5, size=10)
arr

array([1, 3, 0, 0, 1, 4, 1, 1, 4, 1])

In [40]:
arr2 = np.random.randint(5, 10, size=(3, 4))
arr2

array([[9, 5, 9, 6],
       [5, 9, 9, 9],
       [6, 6, 9, 5]])

In [41]:
np.random.seed(123)
np.random.rand(3, 4)

array([[0.69646919, 0.28613933, 0.22685145, 0.55131477],
       [0.71946897, 0.42310646, 0.9807642 , 0.68482974],
       [0.4809319 , 0.39211752, 0.34317802, 0.72904971]])